# -*- coding: utf-8 -*-
"""decision tree 21-05-2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EC6iNLP8-7rDuDSUaHVqirB2w_cjbdH6
"""

import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/apratim777/apratim777/master/salaries.csv")
df.head()

inputs=df.drop('salary_more_then_100k',axis='columns')
inputs

target=df['salary_more_then_100k']
target

from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

inputs['company_name']=le_company.fit_transform(inputs['company'])
inputs['job_name']=le_job.fit_transform (inputs['job'])
inputs['degree_name']=le_degree.fit_transform(inputs['degree'])
inputs

inputs_n=inputs.drop(['company','job','degree'],axis='columns')
inputs_n

target

from sklearn import tree
model=tree.DecisionTreeClassifier()

model.fit(inputs_n,target)

model.score(inputs_n,target)

model.predict([[2,1,1]]) #2- google 1-computer prog.,0-ba

#DTC
import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/apratim777/apratim777/refs/heads/master/salaries.csv')
df

inputs=df.drop(['salary_more_then_100k'],axis='columns')
inputs

target=df['salary_more_then_100k']
target

from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

inputs['company_name']=le_job.fit_transform(inputs['company'])
inputs['job_name']=le_job.fit_transform(inputs['job'])
inputs['degree_name']=le_job.fit_transform(inputs['degree'])
inputs

inputs_n=inputs.drop(['company','job','degree'],axis='columns')
inputs

target

from sklearn import tree
model=tree.DecisionTreeClassifier()

model.fit(inputs_n,target)

model.score(inputs_n,target)

model.pre([2,1,1])

