# -*- coding: utf-8 -*-
"""Multiple linear regresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fb1BwgtP8GMqEzcQ9vi88GqqCptQ1KrD
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

mca=pd.read_csv('https://raw.githubusercontent.com/apratim777/apratim777/refs/heads/master/homeprices1.csv')
mca

mca.bedrooms.median()

mca.bedrooms.max()

mca.bedrooms.min()

mca.bedrooms=mca.bedrooms.fillna(mca.median())
mca

mca.bedrooms=mca.bedrooms.fillna(5)
mca

mca.price

new_x=mca.drop('bedrooms',axis=1)
new_x

new_y=mca.drop('price',axis=1)
new_y

reg=linear_model.LinearRegression()
reg.fit(new_x,new_y)

y1=mca.drop(['bedrooms','age','area'],axis=1)
y1

plt.xlabel='age'
plt.ylabel='price'
plt.scatter(mca.age,mca.price,color='blue',marker='+')
plt.plot(new_x,mca.price)

plt.xlabel='age'
plt.ylabel='price'
plt.scatter(mca.age,mca.price,color='blue',marker='+')
plt.plot(new_x,reg.predict(new_x))

reg.score(new_x,new_y)

