# -*- coding: utf-8 -*-
"""simple logistic regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZT7sU-iEGl1DODWjmu3LZld7p_fSpAGm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

mca=pd.read_csv('https://raw.githubusercontent.com/apratim777/apratim777/refs/heads/master/insurance_data.csv')
mca

mca.head()

mca.tail()

mca.count()

x=mca.drop('bought_insurance',axis=1)
x

y=mca.drop('age',axis=1)
y

plt.figure(figsize=(4,4))
plt.xlabel('bought_insurance')
plt.ylabel('age')
plt.scatter(x,y,color='blue')

from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.6)
train_x

train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.6)
test_x

from sklearn.linear_model import LogisticRegression

reg=LogisticRegression()

reg.fit(train_x,train_y)

y_predict=reg.predict(x)
y_predict

y_predict=reg.predict(test_x)
y_predict

test_x

reg.score(test_x,test_y)

reg.score(train_x,train_y)

plt.figure(figsize=(4,4))
plt.plot(test_x,test_y,color='green')

plt.figure(figsize=(4,4))
plt.plot(train_x,train_y,color='red')

plt.figure(figsize=(4,4))
plt.plot(train_x,reg.predict(train_x),color='blue')

